spring:
  application:
    name: manifest-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:guce_manifest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

guce:
  mode: dev
  kafka:
    topic-manifeste-recu: manifeste.recu

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
