spring.application.name=guce-portal
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

server.port=8090

management.endpoints.web.exposure.include=health,info

# URLs des microservices (dev local)
guce.services.declaration=http://localhost:8080
guce.services.manifest=http://localhost:8081
guce.services.authorization=http://localhost:8082
guce.services.payment=http://localhost:8083
guce.services.inspection=http://localhost:8084
guce.services.pcs=http://localhost:8085
guce.services.reference=http://localhost:8086
guce.services.operator=http://localhost:8087
guce.services.notification=http://localhost:8088
guce.services.audit=http://localhost:8089
